 printf("Name: %s\n awayMatches: %d\n homeMatches: %d\n awayWins: %d\n homeWins: %d\n awayLoses: %d\n homeLoses%d\n awayDraws: %d\n homeDraws: %d\n totalGoalsScored: %d\n totalGoalsConceded: %d\n awayGoalsScored: %d\n homeGoalsScored: %d\n awayGoalsConceded: %d\n homeGoalsConceded: %d\n points: %d",
        teams[1].name,
        teams[1].awayMatches,
        teams[1].homeMatches,
        teams[1].awayWins,
        teams[1].homeWins,
        teams[1].awayLoses,
        teams[1].homeLoses,
        teams[1].awayDraws,
        teams[1].homeDraws,
        teams[1].totalGoalsScored,
        teams[1].totalGoalsConceded,
        teams[1].awayGoalsScored,
        teams[1].homeGoalsScored,
        teams[1].awayGoalsConceded,
        teams[1].homeGoalsConceded,
        teams[1].points
        );
