#include <stdio.h>
#include <stdlib.h>

#define NUMOFROUNDS 33
#define NUMOFMATCHESPRROUND 6
#define NUMOFTOTALMACHTES (NUMOFROUNDS*NUMOFMATCHESPRROUND)
#define NUMOFTEAMS 12
#define TEAMNAMEBUFFER 4
#define WEEKDAYBUFFER 4
#define MAXLINELENGTH 80
#define WINPOINTS 3
#define DRAWPOINTS 1
#define LOOSEPOINTS 0
#define SOURCEFILE "superliga-2015-2016"
